services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server